### ISSUE TITLE
It's not really an issue...

### ISSUE THREAD

**Issue by wind57** [roookeee/datus#37]
I just wanted to tell you that compared to some libraries (even my code, but I am not even ready for a release yet, so I might improve more), your code does a pretty good job. Here are my results run against github actions with latest JMH: https://github.com/wind57/0xMapper/pull/8/checks?check_run_id=820811700

You need to download the artifacts to see them. 

You can close this issue or somehow reference to those, if you want.

**Comment by roookeee** [comment]
Thanks :) Still weird to see mapstruct performing better than the direct mapping - i wouldn't trust the results until that is "fixed" because if I remember correctly they do null checks before their mapping steps... Gl on your mapper, will think about linking the results once they are in your main branch
